### ISSUE TITLE
(syncthing) Outdated

### ISSUE THREAD

**Issue by pauby** [pauby/ChocoPackages#155]
### Checklist

- [X] I have checked the [moderation queue](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) and no new version has been submitted (only visible when logged in), or a version has been submitted but has failed the automated checks.
- [X] The new version is a stable release. Pre-release versions will not be added.
- [X] There are no existing [bug](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Abug) or [outdated](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Aoutdated) issues.
- [X] The new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

1.22.0

**Comment by pauby** [comment]
It appears the way it is updating using GitHub is no longer working. However, there is a problem in the PowerShell module I use for GitHub. I've raised an [issue](https://github.com/microsoft/PowerShellForGitHub/issues/372).

Will update this once it's been released. If it's going to be too much longer, I'll do a manual release.

**Comment by compwiz32** [comment]
Hey @pauby - sorry to mail bomb you... just saw this after I contacted you via email. the problem is the app has an auto updater built into the client and it is doing a partial upgrade on its own and then it fails because of an access error... 

The result is the config.xml file is marked as an upgrade is about to occur and the app can't update. On the next boot, the app won't run... 

So the really short version is... this choco package being out of date now can actually cause the app to fail. 

```
2022-11-03T00:12:36.5871731-04:00:  Automatic upgrade: open C:\ProgramData\chocolatey\lib\syncthing\tools\syncthing-windows-amd64-v1.21.0\syncthing3656369076: Access is denied. 
```

**Comment by pauby** [comment]
I've pushed the new version of syncthing and its making its way through moderation](https://community.chocolatey.org/packages/syncthing/1.22.1#versionhistory).

**Comment by compwiz32** [comment]
thank you!

**Comment by pauby** [comment]
Package approved.
