### ISSUE TITLE
yubico-piv-tool Outdated, latest version 2.3.1

### ISSUE THREAD

**Issue by asheroto** [pauby/ChocoPackages#181]
### Checklist

- [X] I have checked the [moderation queue](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) and no new version has been submitted (only visible when logged in), or a version has been submitted but has failed the automated checks.

- [X] The new version is a stable release. Pre-release versions will not be added.
- [X] There are no existing [bug](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Abug) or [outdated](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Aoutdated) issues.
- [X] The new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

2.3.1

### Download location

https://developers.yubico.com/yubico-piv-tool/Releases/

### Package Page

https://community.chocolatey.org/packages/yubico-piv-tool

**Comment by xlammertink** [comment]
I noticed this issue while checking for the status of a PR I've created for the Yubico Authenticator and noticed this is caused by a failing update script. I've fixed the script and included it into my PR (https://github.com/pauby/ChocoPackages/pull/180) as well.

You can follow the steps in issue https://github.com/pauby/ChocoPackages/issues/179 to manually work around the problem until Pauby has completed the PR.

**Comment by pauby** [comment]
Just as an update to this, I am not ignoring this, but not around to be able to test it. I will _try_ to look at this later today as I appreciate the time for the PR and also people want it updated. Apologies.
