### ISSUE TITLE
(adobereader)

### ISSUE THREAD

**Issue by chimmmpie** [pauby/ChocoPackages#202]
### Checklist

- [X] I have checked the [moderation queue](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) and no new version has been submitted (only visible when logged in), or a version has been submitted but has failed the automated checks.

- [X] The new version is a stable release. Pre-release versions will not be added.
- [X] There are no existing [bug](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Abug) or [outdated](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Aoutdated) issues.
- [X] The new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

23.008.2042X

### Download location

https://www.adobe.com/devnet-docs/acrobatetk/tools/ReleaseNotesDC/continuous/dccontinuousdec2023.html#dccontinuousdectwentytwentythree

### Package Page

https://community.chocolatey.org/packages/adobereader

**Comment by pauby** [comment]
The problem is that Adobe has published version '23.008.2042X' which isn't a valid version number ('X' is not a number). If you go into the page that it links to, you'll see the version number is 23.008.20421. I don't see any reason why they woudn't publish that.

If you look at every recent version they have published, you'll see they all end in a number:

![image](https://github.com/pauby/ChocoPackages/assets/12760779/d57ca7ff-efe9-4fde-b993-3caf60a1a032)

I'm not going to amend the update script, as no doubt it will just need changed back again when they publish a correct version number in future. My suggestion would be to contact Adobe and ask them to publish a correct version number which is consistent with what they have done in the past.

I don't want this to sound as abrupt as it probably does. Hopefully, it doesn't come across that way.

**Comment by chimmmpie** [comment]
@pauby I understand in case u don't want to update the script. But could u publish the update manually. Assuming it's just once. Because now all users won't get the latest version.

**Comment by chimmmpie** [comment]
According to adobe support chat: "The latest version of Acrobat reader is 23.008.20421. The future releases will have the acrobat versions and no X mark.". I have requested them to update there docs. So maybe they will but i doubt it.

**Comment by pauby** [comment]
I manually updated the package to version 2023.8.2042 and tested it.

Upgrade from 2023.6.20380:

![Screenshot_20231223_201427](https://github.com/pauby/ChocoPackages/assets/12760779/b075964e-ff81-47a4-a100-25ed68b01ca7)

![image](https://github.com/pauby/ChocoPackages/assets/12760779/e2afbd08-3508-4834-a96c-85bc49fb1937)

Clean install (after rolling back VM):

![image](https://github.com/pauby/ChocoPackages/assets/12760779/378af1e8-f0e2-4a34-9fd9-d8e21eb389e0)

![image](https://github.com/pauby/ChocoPackages/assets/12760779/71c888c9-8383-4f56-a0ea-e255ad505d2c)


The package files in this repository have not been updated to reflect the changes that were pushed as this was an out-of-band update..
