### ISSUE TITLE
(teamviewer) - please unlist non-working packages and update old versions to direct download links

### ISSUE THREAD

**Issue by bcurran3** [pauby/ChocoPackages#23]
RE: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/chocolatey/g40A-jgCFqU

PROBLEM: The majority of TeamViewer package versions use a generic download URL which always downloads the latest version.  This renders old package versions useless especially when a user wants to install a specific older version.

This really is a big issue with this package for licensed users of TeamViewer who do not upgrade their license every year to the latest version. When using a licensed version, you're licensed through the entire major version. Much of SMB corporate America upgrades programs every other version or so; ala Windows, Office, Quickbooks, etc to defer the high license upgrade cost (Personally: Upgrading my TeamViewer license every six months or a year to the latest versions costs me thousands of dollars and normally has very little to no ROI unless there is an OS compatibility issue). 

I've brought this up before and I believe the maintainers added some older versions with hard links to solve the problem. A quick glance at the dl links for some older versions shows we still have problems. I'll use v13 as an example:

https://chocolatey.org/packages/teamviewer/13.2.26558 dl link 'https://download.teamviewer.com/download/TeamViewer_Setup.exe'
https://chocolatey.org/packages/teamviewer/13.2.14327 dl link https://download.teamviewer.com/download/TeamViewer_Setup.exe'
https://chocolatey.org/packages/teamviewer/13.2.5287   dl link 'https://download.teamviewer.com/download/TeamViewer_Setup.exe'
https://chocolatey.org/packages/teamviewer/13.1.3629   dl link 'https://download.teamviewer.com/download/TeamViewer_Setup.exe'
https://chocolatey.org/packages/teamviewer/13.1.1548   dl link 'https://download.teamviewer.com/download/version_13x/TeamViewer_Setup.exe'
https://chocolatey.org/packages/teamviewer/13.0.6447   dl link 'https://download.teamviewer.com/download/TeamViewer_Setup.exe'

Of a those 6 versions of TeamViewer v13 "available" via Chocolatey, only package v13.1.1548 will actually download and install some version of TeamVeiwer v13. TeamViewer GmbH does do upgrades to older major versions for security and other reasons, so the Chocolatey package v13.1.1548  will install whatever the latest version in the v13 series is (13.2.26558), but it will fail install in most environments  due to checksums.

HERE'S MY SOLUTION:
(for the maintainers)
* Please go through the listed packages for TeamViewer on the Chocolatey Community Repository. Remove all package versions EXCEPT one that has a working download URL for reach major version. If you leave multiples for the current major version, it's up to you. 
* When a new major version of TeamViewer is released (e.g. v15.x) repeat the processes of cleaning up the listings for the previous major version and push a new package version of the previous major TeamViewer version with the major version specific URL.

THE RESULT:
* We'd see multiple listings of the current major version of TeamViewer just like any other package. 
* The garbage older package versions would be delisted, clearing the clutter.
* There would be one working link for older major versions of TeamViewer (e.g. 13.x, 12.x 11.x 10.x etc) that licensed TeamViewer users could rely on working and installing.

FYI: to mainainers, the download URL format for older versions works for current versions as well. i.e. https://download.teamviewer.com/download/version_14x/TeamViewer_Setup.exe will download the latest TeamViewer v14 the same as https://download.teamviewer.com/download/TeamViewer_Setup.exe which is used in current install scripts. Changing to using that link structure would probably be better for future accuracy.

**Comment by pauby** [comment]
My response is based on that only two people have ever brought up the issue of TeamViewer having the same installer for open source versions (the licensed version uses the CDN - I just checked - which will therefore get the correct version).

> Much of SMB corporate America upgrades programs every other version or so; ala Windows, Office, Quickbooks, etc to defer the high license upgrade cost 

Organisations are recommended not to use the Community Repository and instead setup their own internal repository so this will not affect the vast majority of SMB's (Corporate America or otherwise).

> Please go through the listed packages for TeamViewer on the Chocolatey Community Repository. Remove all package versions EXCEPT one that has a working download URL for reach major version. If you leave multiples for the current major version, it's up to you.

> When a new major version of TeamViewer is released (e.g. v15.x) repeat the processes of cleaning up the listings for the previous major version and push a new package version of the previous major TeamViewer version with the major version specific URL.

That would be a good solution for open source users but requires time and the package to be manually managed for every version which defeats the purpose of automating the pushing of new releases. Given the number of people who this affects (taken as the number of people who have brought this up as they were affected) this effort put into this is not worth the return.

> FYI: to mainainers, the download URL format for older versions works for current versions as well. i.e. download.teamviewer.com/download/version_14x/TeamViewer_Setup.exe will download the latest TeamViewer v14 the same as download.teamviewer.com/download/TeamViewer_Setup.exe which is used in current install scripts. Changing to using that link structure would probably be better for future accuracy.

If you (or anybody else) want to pick this up and submit a PR for automating this, ensuring that the continuing process works, I'm happy to look at it.

**Comment by bcurran3** [comment]
Looks like this is a debate again.

Getting you to make improve packages is a constant losing battle. 

You're not a maintainer, you're only an executor of AU.

The package would be better served with a volunteer who wants to maintain it.

The premise behind the request was for you simply unlist non-working packages. It's apparent you don't have the time or willingness to do it. 

The irony is you most likely spent more time writing the four paragraph response and re-editing it then the time it would take to unlist the non-working packages.

**Comment by pauby** [comment]
> The irony is you most likely spent more time writing the four paragraph response

It took me 5 minutues to write it but we'll leave that aside.

GitHub is about collaboration. You want something changed? Raise a PR for it. If you don't want to do that, then that is absolutely fine. But don't expect people to take time out of their day to make changes because _you_ want them. The package exists for _all users_, not just _you_. 900k of downloads says it's working for those users.

If you can't treat people with respect Bill then I have no interest in dealing with you. I have no time for childish tantrums when people don't get what they want. Grow up.
