### ISSUE TITLE
gitter --version 5.0.1 does not install/upgrade

### ISSUE THREAD

**Issue by n3rd4i** [pauby/ChocoPackages#61]
Hi, I've been trying to update this package but I get the following error:
```
T:\>choco install gitter --version 5.0.1
Chocolatey v0.10.15
Installing the following packages:
gitter
By installing you accept licenses for the packages.
Progress: Downloading gitter 5.0.1... 100%

gitter v5.0.1
gitter package files install completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Hashes match.
Hashes match.
Installing gitter...
gitter has been installed.
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot create a file when that file already exists.

The install of gitter was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\gitter\tools\chocolateyInstall.ps1'.
See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
- gitter (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\gitter\tools\chocolateyInstall.ps1'.
See log for details.
```
But the installation on the cloud machine works?

Any help on this is appreciated.
Thanks.

**Comment by pauby** [comment]
I've confirmed that I get this error if I force the install.

![image](https://user-images.githubusercontent.com/12760779/85719855-c0688f80-b6e7-11ea-934d-5645d9934beb.png)

The reason is [this line](https://github.com/pauby/ChocoPackages/blob/master/automatic/gitter/tools/chocolateyInstall.ps1#L21). Not sure why it won't overwrite it. That code was put in there as previous versions of Gitter put the shortcuts into the users profile and not the global one. So it now needs to be removed and a few other `.ignore` files created.

Thanks for pointing it out. Leave it with me.

**Comment by pauby** [comment]
This has been fixed at https://github.com/pauby/ChocoPackages/commit/094b2936bb1a17440d60d9fc49e73c8e53186a39 and the installer has been embedded in the package.
