### ISSUE TITLE
Upgrade of keepass failed but registered new version

### ISSUE THREAD

**Issue by mwisnicki** [pauby/ChocoPackages#73]
Details in https://github.com/chocolatey/choco/issues/2177

**Comment by pauby** [comment]
Looking back on the details of the issue mentioned above, I can see this looks like correct behaviour by Chocolatey (it tried to upgrade the packages shown in the first output which were `keepass` and `keepass.install`). They are two separate packages so a `choco upgrade all` would try and upgrade them one at a time.

The `keepass` package was upgraded after `keepass.install` so I'm guessing here that because `keepass.install` is in the dependency chain (it's a dependency of `keepass`) then it didn't try to install it again when the `keepass` package was being installed.

I actually think this is standard Chocolatey behaviour.

I'm going to go ahead and close this as I simply can't replicate it.

**Comment by mattcargile** [comment]
I just had this happen from `2.50` to `2.51`. I had Keepass open at the time. 

```powershell
You have keepass v2.50 installed. Version 2.51 is available based on your source(s).
Progress: Downloading keepass.install 2.51... 100%
Progress: Downloading keepass 2.51... 100%

keepass.install v2.51 [Approved]
keepass.install package files upgrade completed. Performing other installation steps.
Installing keepass.install...
ERROR: Running ["C:\ProgramData\chocolatey\lib\keepass.install\tools\KeePass-Setup.exe" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- ] was not successful. Exit code was '1'. See log for possible error messages.
The upgrade of keepass.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolateyInstall.ps1'.
 See log for details.

keepass v2.51 [Approved]
keepass package files upgrade completed. Performing other installation steps.
 The upgrade of keepass was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\keepass'
keepass.install is not installed. Installing...

keepass.install v2.51 [Approved]
keepass.install package files upgrade completed. Performing other installation steps.
Installing keepass.install...
ERROR: Running ["C:\ProgramData\chocolatey\lib\keepass.install\tools\KeePass-Setup.exe" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- ] was not successful. Exit code was '1'. See log for possible error messages.
The upgrade of keepass.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolateyInstall.ps1'.
 See log for details.
```

**Comment by mattcargile** [comment]
Created the below issue to track. I've copied the above note there.

https://github.com/pauby/ChocoPackages/issues/138
