### ISSUE TITLE
(gh) Default Install To `gh\tools` For Shim Creation

### ISSUE THREAD

**Issue by mattcargile** [pauby/ChocoPackages#97]
### Feature Request
Would it be reasonable to default the install to `C:\ProgramData\chocolatey\lib\gh\tools\`. So it will create a ["shim"](https://docs.chocolatey.org/en-us/features/shim) for the exe into the `"$env:ChocolateyInstall\bin"` directory? By default it is installing into `${env:ProgramFiles(x86)}\GitHub CLI\`. 

It would clean up my `$env:PATH` a little. Many other command line tools default to this behavior such as the sysinternals tool set, fzf, fd, ripgrep, etc.

### Workaround
Passed directly to installer. Not the ideal scenario as I had to know this would be the path.
`choco install gh -y --ia='INSTALLDIR=C:\ProgramData\chocolatey\lib\gh\tools\'`

### Solution
Pass the `INSTALLDIR` to the `msi` installer or install by unzipping to the directory.

**Comment by pauby** [comment]
The default install location is dictated by the MSI installer and most people are going to expect it there.

The Sysinternals tool set, fzf, fd and ripgrep don't have installers. They are Zip files that are extracted to the package directory (which is expected behaviour again).

To remove `gh` from the path the package would have to stop using the installer.

I understand what you're asking but I balancing the amount of work to do this vs the amount of benefit gained (in fact the opposite, as it changes expected behaviour) is something that would be beneficial.
